apiVersion: apps/v1
kind: Deployment
metadata:
  name: messagereceivertest
  labels:
    app: messagereceivertest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: messagereceivertest
  template:
    metadata:
      labels:
        app: messagereceivertest
        version: 0.1.0
    spec:
      containers:
      - name: messagereceivertest
        image: <CONTAINER_REGISTRY>/messagereceivertest:latest
        imagePullPolicy: Always
        env:
        - name: ServiceBusConnectionString
          value: ""
        - name: QueueName
          value: "testqueue"
